name: "Terraform Deployment"

on:
  push:
    branches:
      - main
      - '*'
  pull_request:

jobs:
  terraform:
    name: "Terraform Plan or Apply"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1
      PREFIX: ka37  

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        working-directory: ./terraform 
        run: terraform init

      - name: Terraform Plan
        if: github.ref != 'refs/heads/main'
        id: plan
        working-directory: ./terraform 
        run: terraform plan -var="prefix=$PREFIX" -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: github.ref != 'refs/heads/main' && steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ./terraform 
        run: terraform apply -var="prefix=$PREFIX" -auto-approve
