name: "SAM Deployment"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy_sam:
    name: "Build and Deploy SAM Application"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1
      PREFIX: ka37  # Your candidate number or project identifier

    steps:
      # Checkout the repository
      - name: Check out the repo
        uses: actions/checkout@v3

      # Install Python 3.8
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Verify SAM CLI installation
      - name: Verify SAM CLI installation
        run: sam --version

      # Build the SAM application
      - name: Build SAM application
        run: sam build -t sam_lambda/ka37/template.yaml

      # Deploy the SAM application
      - name: Deploy SAM application
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name ka37-stack \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
