name: Terraform Deploy

on:
  push:
    branches:
      - main
      - '*'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: "eu-west-1"  # Directly setting the region here
      TF_VAR_prefix: "ka37"           # Example prefix, customize if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"  # Hardcoding the region here

      - name: Initialize Terraform
        id: init
        working-directory: ./infra 
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.ref != 'refs/heads/main'
        working-directory: ./infra 
        run: terraform plan -var="prefix=${{ env.TF_VAR_prefix }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./infra 
        run: terraform apply -auto-approve -var="prefix=${{ env.TF_VAR_prefix }}"
