name: "Deploy SAM Application"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy_sam:
    name: "Build and Deploy SAM Application"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1
      PREFIX: ka37  # Your candidate number or project identifier

    steps:
      # Checkout the repository
      - name: Check out the repo
        uses: actions/checkout@v3

      # Install AWS SAM CLI
      - name: Install SAM CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          curl -Lo sam_installation.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          unzip sam_installation.zip -d sam-installation
          sudo ./sam-installation/install

      # Verify SAM CLI installation
      - name: Verify SAM CLI installation
        run: sam --version

      # Build the SAM application
      - name: Build SAM application
        run: sam build -t sam_lambda/ka37/template.yml

      # Deploy the SAM application
      - name: Deploy SAM application
        run: |
          sam deploy \
            --template-file sam_lambda/ka37/.aws-sam/build/template.yaml \
            --stack-name ka37-stack \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
